FROM nginx:alpine

# 1. Copy config
# Context is Root, so we must specify "webapp/default.conf"
COPY webapp/default.conf /etc/nginx/conf.d/default.conf

# 2. Copy Flutter files
# Context is Root, so we can see "mobile/" directly
COPY mobile/build/web /usr/share/nginx/html